import type {GetStaticPaths, GetStaticProps, NextPage} from "next";
import type {ParsedUrlQuery} from "querystring";
import { ObjectAPI, Proj } from "../../types/types";
import { getProjectsAR, getProject } from "../../services/getDataAPI";
import Project from "../../src/components/Project";
import Head from "next/head";

interface Props {
  project: ObjectAPI;
}

interface Params extends ParsedUrlQuery {
  id: string;
}

export const getStaticProps: GetStaticProps<Props, Params> = async ({params}) => {
  const {id} = params as Params;
  const project = await getProject(id)

  if (!project) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      project,
    },
  };
};

export const getStaticPaths: GetStaticPaths = async () => {
  const listProjects = await getProjectsAR();
  const projects = listProjects.projects.project;

  return {
    paths: projects.map((project: any) => ({
      params: {
        id: project.id.toString(),
      },
    })),
    fallback: "blocking",
  };
};

const projects: NextPage<Props> = ({project}) => {
  const title = project.projects.project[0].title;

  return (
    <>
      <Head>
        <title>Argentina ayuda | {title}</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="shortcut icon" href='../logo-sun.ico' /> */}
      </Head>

      <div style={{display: "flex", flexDirection: "column", alignItems: "center"}}>
        <Project data={project.projects.project[0]} location='project' portada={false} />
      </div>
    </>
  );
};

export default projects;