import Head from 'next/head'
import Image from 'next/image'
import React, {useState} from 'react'
import logo from '../src/assets/logo-footer.png'

const about = () => {
  return (
    <>
      <Head>
        <title>Argentina ayuda | Acerca de</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className='flex flex-wrap items-center justify-center'>
        <div className='flex content-center flex-wrap w-10/12 bg-cyan-50 px-16 py-8 rounded'>
          <div className='w-9/12'>
            <section className='w-full'>
              <h2 className='font-bold text-2xl py-4'>
                ¿Quienes sómos?
              </h2>
              <p className="block rounded py-4 text-lg w-5/6">
                En realidad quien escribe soy yo solo, les cuento un poco sobre mí. <br />
                Me llamo David Benedette, tengo 24 años y vivo en Bahía Blanca, aunque soy oriundo
                de General Lamadrid, ambas ciudades pertenecientes a la provincia de
                Buenos Aires, Argentina. <br />
                Soy un estudiante de programación que está buscando su primer empleo
                en el mercado de la tecnología. <br />
                Este fue el motivante para crear este sitio web, porque creo que ayudando
                a los demás, como efecto colateral también pueden ayudarnos a nosotros. <br />
              </p>
            </section>

            <section className='w-full'>
              <h2 className='font-bold text-2xl py-4'>
                ¿Como surgió Argentina Ayuda?
              </h2>
              <p className="block rounded py-4 text-lg w-5/6">
                Al principio no sabía de que manera podía ayudar a otros por medio de mis
                conocimientos en programación. Entonces empecé a buscar diferentes formas 
                pero ninguna me satisfacía.
                Y en ese momento pensé, ¿y si ayudo a que otros ayuden? Es una consigna simple 
                y clara. <br /> De esta manera surgió la necesidad de buscar proyectos que precisen 
                de nuestra colaboración, pero nuevamente surgieron nuevos interrogantes: 
                ¿Por qué los demás ayudarían en un solo proyecto? ¿Es mas conveniente ayudar
                en temas de salud o de educación? ¿Por qué cerrarse a una sola temática? <br /> 
                Preguntando y repreguntando surgen las mejores ideas. Es lo que me llevó al 
                principio a querer abarcar lo máximo posible, aunque con el paso del tiempo 
                se me ocurrió otra idea: ¿Y si ayudamos en muchos proyectos pero que sean 
                cercanos a nosotros? <br />
                Y ahí dí con el clavo, argentinos ayudando a otros argentinos. Era obvio,
                es algo que se ve todos los dias aunque parezca lo contrario. 
                Comedores, merenderos, clubes deportivos, sociedades de fomento, etc.
                todas asociaciones que ayudan incansablemente a la comunidad.  <br />
                Así, surgió Argentina Ayuda, un sitio web que conecta las necesidades de
                los ciudadanos argentinos con gente que está dispuesta a "dar una mano", como 
                se dice acá. 
              </p>
            </section>

            <section className='w-full'>
              <h2 className='font-bold text-2xl py-4'>
                ¿Cómo se puede ayudar?
              </h2>
              <p className="block rounded py-4 text-lg w-5/6">
                Siempre que te sea interesante un proyecto, podés navegar desde su
                página particular hacia el sitio "Global Giving" que te permite
                hacer donaciones en las cantidades que desees, a través de diferentes
                medios de pago. <br />
                La otra forma es compartiendo este sitio entre tus contactos y en 
                redes sociales, para que más personas tengan la posibilidad de
                conocer otras realidades y poder ayudar de una forma fácil y rápida. 
              </p>
            </section>
          </div>
        <div className='w-3/12 pt-8'>
          <Image src={logo} className="object-contain" />
        </div>
        </div>
      </div>
    </>
  )
}

export default about