import Head from 'next/head'
import Image from 'next/image'
import logo from '../src/assets/logo-footer.png'

const about = () => {
  return (
    <>
      <Head>
        <title>Argentina ayuda | About</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className='flex flex-wrap items-center justify-center'>
        <div className='flex content-center flex-wrap md:w-10/12 text-center md:text-left bg-cyan-50 w-full px-8 md:px-16 py-8 rounded'>
          <div className='w-full m-auto md:w-9/12 order-2 md:order-1'>
            <section className='w-full'>
              <h2 className='font-bold pt-8 pb-4 text-2xl md:pt-16'>
                About us?
              </h2>
              <p className="rounded text-lg">
                Actually, I am the only one who writes, I tell you a little about myself. <br />
                My name is David Benedette, I am 24 years old and I live in Bahía Blanca, although I am a native
                of General Lamadrid, both cities belonging to the province of
                Buenos Aires, Argentina. <br />
                I am a programming student looking for his first job
                in the technology market.<br />
                This was the motivation to create this website, because I believe that helping
                to others, as a side effect they can also help us. <br />
              </p>
            </section>

            <section className='w-full'>
              <h2 className='font-bold pt-8 pb-4 text-2xl md:pt-16'>
                How did Argentina Ayuda come about?
              </h2>
              <p className="rounded text-lg">
                At first I did not know how I could help others through my
                knowledge in programming. So I started looking for different ways
                but none satisfied me.
                And at that moment I thought, what if I help others to help? It&apos;s a simple slogan
                and clear. <br /> 
                In this way, the need arose to look for projects that require
                of our collaboration, but again new questions arose:
                Why would others help on just one project? Is it more convenient to help
                in health or education? Why close to a single theme? <br /> 
                Asking and cross-questioning give rise to the best ideas. It&apos;s what led me to
                beginning to want to cover as much as possible, although with the passage of time
                another idea occurred to me: what if we help in many projects but that they are
                close to us? <br />
                And there I hit the nail on the head, Argentines helping other Argentines. It was obvious,
                It is something that is seen every day even if it seems otherwise.
                Canteens, picnic areas, sports clubs, promotion societies, etc.
                all associations that tirelessly help the community.  <br />
                Thus, Argentina Ayuda emerged, a website that connects the needs of
                Argentine citizens with people who are willing to &apos;&apos;give a hand&apos;&apos;, such as
                it is said here.
              </p>
            </section>

            <section className='w-full'>
              <h2 className='font-bold pt-8 pb-4 text-2xl md:pt-16'>
                How can you help?
              </h2>
              <p className="rounded text-lg">
                Whenever a project is interesting to you, you can browse from its
                particular page to the &apos;&apos;Global Giving&apos;&apos; site that allows you
                make donations in the amounts you want, through different
                payment methods. <br />
                The other way is by sharing this site among your contacts and in
                social networks, so that more people have the possibility of
                know other realities and be able to help in an easy and fast way.
              </p>
            </section>
          </div>
        <div className='w-full mx-auto md:w-3/12 md:pt-8 order-1 md:order-2'>
          <Image src={logo} className="object-contain" alt="Logo" />
        </div>
        </div>
      </div>
    </>
  )
}

export default about